"""
此代码为designer界面设计后生成的MainWindowUI.ui文件直接转换为Python代码而来
实现了软件的功能界面
"""
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(691, 458)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 651, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(11)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout.addWidget(self.label_1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.open_btn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(11)
        self.open_btn.setFont(font)
        self.open_btn.setObjectName("open_btn")
        self.horizontalLayout.addWidget(self.open_btn)
        self.resultdisplay = QtWidgets.QGroupBox(self.centralwidget)
        self.resultdisplay.setGeometry(QtCore.QRect(240, 170, 421, 231))
        self.resultdisplay.setObjectName("resultdisplay")
        self.textEdit = QtWidgets.QTextEdit(self.resultdisplay)
        self.textEdit.setGeometry(QtCore.QRect(10, 120, 401, 101))
        self.textEdit.setObjectName("textEdit")
        self.sectionleft = QtWidgets.QLabel(self.resultdisplay)
        self.sectionleft.setGeometry(QtCore.QRect(20, 30, 91, 20))
        self.sectionleft.setObjectName("sectionleft")
        self.sectionright = QtWidgets.QLabel(self.resultdisplay)
        self.sectionright.setGeometry(QtCore.QRect(20, 60, 91, 20))
        self.sectionright.setObjectName("sectionright")
        self.leftvalue = QtWidgets.QLineEdit(self.resultdisplay)
        self.leftvalue.setGeometry(QtCore.QRect(110, 30, 61, 21))
        self.leftvalue.setObjectName("leftvalue")
        self.rightvalue = QtWidgets.QLineEdit(self.resultdisplay)
        self.rightvalue.setGeometry(QtCore.QRect(110, 60, 61, 21))
        self.rightvalue.setObjectName("rightvalue")
        self.Max = QtWidgets.QGroupBox(self.resultdisplay)
        self.Max.setGeometry(QtCore.QRect(190, 20, 101, 91))
        self.Max.setObjectName("Max")
        self.maxx = QtWidgets.QLabel(self.Max)
        self.maxx.setGeometry(QtCore.QRect(10, 30, 21, 16))
        self.maxx.setObjectName("maxx")
        self.maxy = QtWidgets.QLabel(self.Max)
        self.maxy.setGeometry(QtCore.QRect(10, 60, 21, 20))
        self.maxy.setObjectName("maxy")
        self.maxxvalue = QtWidgets.QLineEdit(self.Max)
        self.maxxvalue.setGeometry(QtCore.QRect(30, 30, 61, 20))
        self.maxxvalue.setObjectName("maxxvalue")
        self.maxyvalue = QtWidgets.QLineEdit(self.Max)
        self.maxyvalue.setGeometry(QtCore.QRect(30, 60, 61, 20))
        self.maxyvalue.setObjectName("maxyvalue")
        self.Min = QtWidgets.QGroupBox(self.resultdisplay)
        self.Min.setGeometry(QtCore.QRect(300, 20, 101, 91))
        self.Min.setObjectName("Min")
        self.minyvalue = QtWidgets.QLineEdit(self.Min)
        self.minyvalue.setGeometry(QtCore.QRect(30, 60, 61, 20))
        self.minyvalue.setObjectName("minyvalue")
        self.miny = QtWidgets.QLabel(self.Min)
        self.miny.setGeometry(QtCore.QRect(10, 60, 21, 20))
        self.miny.setObjectName("miny")
        self.minx = QtWidgets.QLabel(self.Min)
        self.minx.setGeometry(QtCore.QRect(10, 30, 21, 16))
        self.minx.setObjectName("minx")
        self.minxvalue = QtWidgets.QLineEdit(self.Min)
        self.minxvalue.setGeometry(QtCore.QRect(30, 30, 61, 20))
        self.minxvalue.setObjectName("minxvalue")
        self.extre_btn = QtWidgets.QPushButton(self.resultdisplay)
        self.extre_btn.setGeometry(QtCore.QRect(30, 90, 131, 21))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(8)
        self.extre_btn.setFont(font)
        self.extre_btn.setObjectName("extre_btn")
        self.methods = QtWidgets.QGroupBox(self.centralwidget)
        self.methods.setGeometry(QtCore.QRect(20, 70, 211, 331))
        self.methods.setObjectName("methods")
        self.cubic_btn = QtWidgets.QRadioButton(self.methods)
        self.cubic_btn.setGeometry(QtCore.QRect(10, 50, 171, 41))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(14)
        font.setStrikeOut(False)
        self.cubic_btn.setFont(font)
        self.cubic_btn.setObjectName("cubic_btn")
        self.lagrange_btn = QtWidgets.QRadioButton(self.methods)
        self.lagrange_btn.setGeometry(QtCore.QRect(10, 20, 171, 41))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(14)
        self.lagrange_btn.setFont(font)
        self.lagrange_btn.setObjectName("lagrange_btn")
        self.poly_btn = QtWidgets.QRadioButton(self.methods)
        self.poly_btn.setGeometry(QtCore.QRect(10, 160, 191, 41))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(14)
        self.poly_btn.setFont(font)
        self.poly_btn.setObjectName("poly_btn")
        self.degree_label = QtWidgets.QLabel(self.methods)
        self.degree_label.setGeometry(QtCore.QRect(30, 230, 81, 21))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(9)
        self.degree_label.setFont(font)
        self.degree_label.setObjectName("degree_label")
        self.degree_spb = QtWidgets.QSpinBox(self.methods)
        self.degree_spb.setGeometry(QtCore.QRect(110, 230, 71, 22))
        self.degree_spb.setObjectName("degree_spb")
        self.start_btn = QtWidgets.QPushButton(self.methods)
        self.start_btn.setGeometry(QtCore.QRect(20, 270, 171, 51))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(14)
        self.start_btn.setFont(font)
        self.start_btn.setObjectName("start_btn")
        self.splinemethod = QtWidgets.QComboBox(self.methods)
        self.splinemethod.setGeometry(QtCore.QRect(30, 90, 151, 22))
        self.splinemethod.setObjectName("splinemethod")
        self.splinemethod.addItem("")
        self.splinemethod.addItem("")
        self.nature1 = QtWidgets.QLabel(self.methods)
        self.nature1.setGeometry(QtCore.QRect(30, 120, 101, 16))
        self.nature1.setObjectName("nature1")
        self.nature2 = QtWidgets.QLabel(self.methods)
        self.nature2.setGeometry(QtCore.QRect(30, 140, 101, 16))
        self.nature2.setObjectName("nature2")
        self.clamped1 = QtWidgets.QLabel(self.methods)
        self.clamped1.setGeometry(QtCore.QRect(30, 120, 101, 16))
        self.clamped1.setObjectName("clamped1")
        self.clamped2 = QtWidgets.QLabel(self.methods)
        self.clamped2.setGeometry(QtCore.QRect(30, 140, 101, 16))
        self.clamped2.setObjectName("clamped2")
        self.value1 = QtWidgets.QLineEdit(self.methods)
        self.value1.setGeometry(QtCore.QRect(130, 120, 51, 16))
        self.value1.setObjectName("value1")
        self.value2 = QtWidgets.QLineEdit(self.methods)
        self.value2.setGeometry(QtCore.QRect(130, 140, 51, 16))
        self.value2.setObjectName("value2")
        self.squaremethod = QtWidgets.QComboBox(self.methods)
        self.squaremethod.setGeometry(QtCore.QRect(30, 200, 151, 22))
        self.squaremethod.setObjectName("squaremethod")
        self.squaremethod.addItem("")
        self.squaremethod.addItem("")
        self.squaremethod.addItem("")
        self.datacalcultate = QtWidgets.QGroupBox(self.centralwidget)
        self.datacalcultate.setGeometry(QtCore.QRect(390, 70, 271, 91))
        self.datacalcultate.setObjectName("datacalcultate")
        self.predictinput = QtWidgets.QLabel(self.datacalcultate)
        self.predictinput.setGeometry(QtCore.QRect(10, 30, 72, 20))
        self.predictinput.setObjectName("predictinput")
        self.predictoutput = QtWidgets.QLabel(self.datacalcultate)
        self.predictoutput.setGeometry(QtCore.QRect(10, 60, 72, 20))
        self.predictoutput.setObjectName("predictoutput")
        self.predictinputdata = QtWidgets.QLineEdit(self.datacalcultate)
        self.predictinputdata.setGeometry(QtCore.QRect(70, 30, 141, 21))
        self.predictinputdata.setObjectName("predictinputdata")
        self.predictoutputdata = QtWidgets.QLineEdit(self.datacalcultate)
        self.predictoutputdata.setGeometry(QtCore.QRect(70, 60, 141, 21))
        self.predictoutputdata.setObjectName("predictoutputdata")
        self.calculatebutton = QtWidgets.QPushButton(self.datacalcultate)
        self.calculatebutton.setGeometry(QtCore.QRect(220, 30, 41, 51))
        self.calculatebutton.setObjectName("calculatebutton")
        self.Precision = QtWidgets.QGroupBox(self.centralwidget)
        self.Precision.setGeometry(QtCore.QRect(239, 70, 141, 91))
        self.Precision.setObjectName("Precision")
        self.precisionlabel = QtWidgets.QLabel(self.Precision)
        self.precisionlabel.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.precisionlabel.setObjectName("precisionlabel")
        self.precision_spb = QtWidgets.QSpinBox(self.Precision)
        self.precision_spb.setGeometry(QtCore.QRect(20, 50, 101, 31))
        self.precision_spb.setObjectName("precision_spb")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 691, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Curve Fitting Tool"))
        self.label_1.setText(_translate("MainWindow", "选择数据文件："))
        self.open_btn.setText(_translate("MainWindow", "打开"))
        self.resultdisplay.setTitle(_translate("MainWindow", "ResultDisplay"))
        self.sectionleft.setText(_translate("MainWindow", "区间左端点："))
        self.sectionright.setText(_translate("MainWindow", "区间右端点："))
        self.Max.setTitle(_translate("MainWindow", "Max"))
        self.maxx.setText(_translate("MainWindow", "x:"))
        self.maxy.setText(_translate("MainWindow", "y:"))
        self.Min.setTitle(_translate("MainWindow", "Min"))
        self.miny.setText(_translate("MainWindow", "y:"))
        self.minx.setText(_translate("MainWindow", "x:"))
        self.extre_btn.setText(_translate("MainWindow", "计算最值"))
        self.methods.setTitle(_translate("MainWindow", "Methods"))
        self.cubic_btn.setText(_translate("MainWindow", "三次样条插值"))
        self.lagrange_btn.setText(_translate("MainWindow", "拉格朗日插值"))
        self.poly_btn.setText(_translate("MainWindow", "最小二乘拟合"))
        self.degree_label.setText(_translate("MainWindow", "输入阶数："))
        self.start_btn.setText(_translate("MainWindow", "开始拟合"))
        self.splinemethod.setItemText(0, _translate("MainWindow", "自然样条"))
        self.splinemethod.setItemText(1, _translate("MainWindow", "紧压样条"))
        self.nature1.setText(_translate("MainWindow", "左端点二阶导:"))
        self.nature2.setText(_translate("MainWindow", "右端点二阶导:"))
        self.clamped1.setText(_translate("MainWindow", "左端点一阶导:"))
        self.clamped2.setText(_translate("MainWindow", "右端点一阶导:"))
        self.squaremethod.setItemText(0, _translate("MainWindow", "常规"))
        self.squaremethod.setItemText(1, _translate("MainWindow", "指数化处理"))
        self.squaremethod.setItemText(2, _translate("MainWindow", "对数化处理"))
        self.datacalcultate.setTitle(_translate("MainWindow", "DataCalculate"))
        self.predictinput.setText(_translate("MainWindow", "输入x："))
        self.predictoutput.setText(_translate("MainWindow", "预测值："))
        self.calculatebutton.setText(_translate("MainWindow", "计算"))
        self.Precision.setTitle(_translate("MainWindow", "Precision"))
        self.precisionlabel.setText(_translate("MainWindow", "保留小数位数："))
